services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    # mem_limit: 2048m
    # mem_reservation: 1024m
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
