services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    mem_limit: 2048m
    mem_reservation: 1024m
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      minio:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - app-network