services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - ./.env
    depends_on:
      minio:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    external: true