services:
  frontend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - next_static_volume:/app/.next/static
    env_file:
      - ./.env.production
    restart: unless-stopped
    environment:
      HOSTNAME: '0.0.0.0'
    networks:
      - app-network

volumes:
  next_static_volume:
    name: next_static_volume

networks:
  app-network:
    external: true