services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

networks:
  app-network:
    external: true