services:
  frontend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true